import cn from 'classnames'
import Head from 'next/head'
import Link from 'next/link'

import ThemeToggler from '@/components/ThemeToggler'
import styles from '@/styles/Home.module.css'

export default function Header() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={cn(styles.header, 'dark:bg-black dark:text-white')}>
        <div></div>
        <div>
          <Link href="/">Header</Link>
        </div>
        <ThemeToggler />
      </header>
    </>
  )
}
